import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
/*
Components
*/

const TechPanelFrame = ({ meshProps, materialProps }) => {
  /*
  References
  */
  const group = useRef();
  /*
  useGLTF Section
  */
  const { nodes } = useGLTF('/assets/glTF/techPanel_3_draco.glb');

  /*
  JSX
  */
  return (
    <mesh
      {...meshProps}
      ref={group}
      dispose={null}
      geometry={nodes.techPanel.geometry}
      // rotation={[Math.PI / 2, 0, 0]}
      rotation={[0, Math.PI, Math.PI]}

      //   {...frameMeshProps}
    >
      <meshBasicMaterial {...materialProps} />
    </mesh>
  );
};

export default TechPanelFrame;

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx


import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/techPanel_2_draco.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.outherPanelSide001.geometry} material={materials['default']} position={[0.17, 0.75, 0]} />
    </group>
  )
}

useGLTF.preload('/techPanel_2_draco.glb')
*/
