import React, { Suspense, useEffect } from 'react';
//, { useRef, useEffect }
// import { useThree } from '@react-three/fiber';
/*
Components
*/
import SpinningBox from '../../../spinningBox/SpinningBox';
/*
Global State Staf
*/
import { useSnapshot } from 'valtio';
import { canvasState } from '../../../../../../states/canvasState';
/*
Spring data
*/
import { a, useSpring } from '@react-spring/three';
/*
Hook Staff
*/
import useWindowSize from '../../../../../../hooks/useWindowSize';
/*
Assets
import all images  
*/
import containerAbout_Slide0_box1_image1 from '../../../../../../assets/textures/containerAbout_Slide0_box1_image1.png';
import containerAbout_Slide0_box1_image2 from '../../../../../../assets/textures/containerAbout_Slide0_box1_image2.png';
/*
 Basic Data
 */
import {
  slide0Box1Layout,
  slide0Box1Data,
  slide0Box2Layout,
  slide0Box2Data,
} from './slidesData';

const [mobile, desktop] = [850, 1000];

/*
----------------------------------------------------------------------
*/
const Slide0Test = React.forwardRef(({ slideId }, ref) => {
  /*
  References
  */
  // const group = useRef();
  /*
  Hook Section
  Why this hook?
  */
  const windowSize = useWindowSize();

  useEffect(() => {
    // console.log('lide0Box1Layout.mobile. scale', slide0Box1Layout.mobile.scale);
    if (windowSize.width < mobile) {
      console.log('Slide0Test / mobile layout');
    } else {
      console.log('Slide0Test / desktop layout');
    }
  }, [windowSize.width]);

  /*
  Global State Section
    {containerAboutSlideIndex: 0,...}
  */
  const canvasGlobalState = useSnapshot(canvasState);
  /*
  useThree() Staff
  */
  // const { viewport } = useThree();

  /*
  Spring for TextVerses
  */
  const springSlideContent = useSpring({
    from: { position: [0, 0, -2] },
    to: {
      position: [
        0,
        0,
        /*
        in case of Slider1 this second condition is mandatory; otherwise slide is animated befor user enters "containerAbout";
        */
        canvasGlobalState.currentContainer === 'aboutContainer' &&
        slideId === canvasGlobalState.containerAboutSlideIndex
          ? 0
          : slideId < canvasGlobalState.containerAboutSlideIndex
          ? 0
          : -2,
      ],
    },
    config: { mass: 10, tension: 70, friction: 30 },
  });

  /*
  Spring for main group
  */
  const springGroup = useSpring({
    from: { position: [0, 0, 0] },
    to: {
      position: [
        0,
        /*
        in case of Slider) this second condition is mandatory; otherwise slide is animated befor user enters "containerAbout";
        */
        canvasGlobalState.currentContainer === 'aboutContainer' &&
        slideId < canvasGlobalState.containerAboutSlideIndex
          ? 1
          : 0,
        0,
      ],
    },
    config: { mass: 10, tension: 70, friction: 30 },
  });
  /*
  JSX
  What is "GroupForAnimationLevelSlide"?
  What is "GroupForAnimationLevelSlideContent"
  */
  return (
    <a.group
      name="GroupForAnimationLevelSlide"
      ref={ref}
      // scale={[0,0,0]}
      position={springGroup.position}
    >
      {/*-----Body Section------------------------------------------*/}
      <Suspense fallback={null}>
        <a.group
          name="GroupForAnimationLevelSlideContent"
          position={springSlideContent.position}
        >
          <SpinningBox
            groupProps={{
              name: 'groupForSpinningBox_slide_0_Box_1_Data',
              // scale: slide0Box1Layout.mobile.scale,
              // position: slide0Box1Layout.mobile.position,
              // scale: [0.25, 0.25, 0.25],
              // position: [0, -0.01, 0],
              // slide0Box1Layout.mobile.scale,
              scale:
                windowSize.width < mobile
                  ? slide0Box1Layout.mobile.scale
                  : slide0Box1Layout.desktop.scale,
              position:
                windowSize.width < mobile
                  ? slide0Box1Layout.mobile.position
                  : slide0Box1Layout.desktop.position,
              // ...slide0Box1Layout.mobile,
            }}
            spinningBoxConfig={slide0Box1Data}
            /*
            set value of rotation generated by useFrame()
            */
            setRotationYSpeed={0.1}
            /*
            set initial value of rotation for "DragRotateStepByStep"
            */
            setDragRotationX={Math.PI * -0.02}
            /*
            array of images that goes to
            */
            images={[
              containerAbout_Slide0_box1_image1,
              containerAbout_Slide0_box1_image2,
            ]}
            portrait={true}
          />
          <SpinningBox
            groupProps={{
              name: 'groupForSpinningBox_slide_0_Box_2_Data',
              scale:
                windowSize.width < mobile
                  ? slide0Box2Layout.mobile.scale
                  : slide0Box2Layout.desktop.scale,
              position:
                windowSize.width < mobile
                  ? slide0Box2Layout.mobile.position
                  : slide0Box2Layout.desktop.position,
            }}
            spinningBoxConfig={slide0Box2Data}
            setRotationYSpeed={-0.12}
            banner={true}
          />
        </a.group>
      </Suspense>
    </a.group>
  );
});

export default Slide0Test;

/*
  useEffect Test
  */
// useEffect(() => {
//   console.log('slideId:', slideId);
//   console.log(
//     'canvasGlobalState.containerAboutSlideIndex:',
//     canvasGlobalState.containerAboutSlideIndex
//   );
//   console.log(
//     'canvasGlobalState.currentContainer:',
//     canvasGlobalState.currentContainer
//   );
// }, [
//   slideId,
//   canvasGlobalState.containerAboutSlideIndex,
//   canvasGlobalState.currentContainer,
// ]);
// console.log('textHeader.position:', textHeader.position);
