import React, { Suspense, useRef } from 'react';
//, { useRef, useEffect }
import { useFrame } from '@react-three/fiber';
/*
Components
*/
import SpinningBox from '../../../spinningBox/SpinningBox';
/*
Global State Staf
*/
import { useSnapshot } from 'valtio';
import { canvasState } from '../../../../../../states/canvasState';
/*
Spring data
*/
import { a, useSpring } from '@react-spring/three';
/*
Hook Staff
*/
import useWindowSize from '../../../../../../hooks/useWindowSize';
/*
Assets
import images for <SpinningBox> / <SpinningBoxSide> / <UniversalCanvas> / image  
*/
import containerAbout_Slide0_box1_image1 from '../../../../../../assets/textures/containerAbout_Slide0_box1_image1.png';
import containerAbout_Slide0_box1_image2 from '../../../../../../assets/textures/containerAbout_Slide0_box1_image2.png';
import containerAbout_Slide0_box2_image1 from '../../../../../../assets/textures/movingPeople.png';

/*
 Basic Data
 */
import {
  slide0Box1Layout,
  slide0Box1Data,
  slide0Box2Layout,
  slide0Box2Data,
} from './slidesData';

const [minForTablet, desktop] = [850, 1000];

/*
----------------------------------------------------------------------
*/
const Slide0Test = React.forwardRef(({ slideId }, ref) => {
  /*
  References
  */
  const box1 = useRef();
  const box2 = useRef();

  /*
  Hook Section
  Why this hook?
  */
  const windowSize = useWindowSize();
  /*
  Global State Section
    {containerAboutSlideIndex: 0,...}
  */
  const canvasGlobalState = useSnapshot(canvasState);

  /*
  Spring for 
  */
  const springSlideContent = useSpring({
    from: { position: [0, 0, -2] },
    to: {
      position: [
        0,
        0,
        /*
        in case of Slider1 this second condition is mandatory; otherwise slide is animated befor user enters "containerAbout";
        */
        canvasGlobalState.currentContainer === 'aboutContainer' &&
        slideId === canvasGlobalState.containerAboutSlideIndex
          ? 0
          : slideId < canvasGlobalState.containerAboutSlideIndex
          ? 0
          : -2,
      ],
    },
    config: { mass: 10, tension: 70, friction: 30 },
  });

  /*
  Spring for main group
  */
  const springGroup = useSpring({
    from: { position: [0, 0, 0] },
    to: {
      position: [
        0,
        /*
        in case of Slider) this second condition is mandatory; otherwise slide is animated befor user enters "containerAbout";
        */
        canvasGlobalState.currentContainer === 'aboutContainer' &&
        slideId < canvasGlobalState.containerAboutSlideIndex
          ? 1
          : 0,
        0,
      ],
    },
    config: { mass: 10, tension: 70, friction: 30 },
  });
  /*
  JSX
  What is "GroupForAnimationLevelSlide"?
  What is "GroupForAnimationLevelSlideContent"
  */
  return (
    <a.group
      name="GroupForAnimationLevelSlide"
      ref={ref}
      // scale={[0,0,0]}
      position={springGroup.position}
    >
      {/*-----Body Section------------------------------------------*/}
      <Suspense fallback={null}>
        <a.group
          name="GroupForAnimationLevelSlideContent"
          position={springSlideContent.position}
        >
          <SpinningBox
            groupProps={{
              name: 'groupForSpinningBox_slide_0_Box_1_Data',
              /*
              a bit of responsiveness; 
              */
              scale:
                windowSize.width < minForTablet
                  ? slide0Box1Layout.mobile.scale
                  : slide0Box1Layout.desktop.scale,
              position:
                windowSize.width < minForTablet
                  ? slide0Box1Layout.mobile.position
                  : slide0Box1Layout.desktop.position,
              // ...slide0Box1Layout.mobile,
            }}
            /*
            array of props; using map() we get 4 <SpinningBoxSide>
            */
            spinningBoxConfig={slide0Box1Data}
            /*
            array of images ultimately used in <UniversalCanvas>
            */
            images={[
              containerAbout_Slide0_box1_image1,
              containerAbout_Slide0_box1_image2,
              containerAbout_Slide0_box1_image1,
              containerAbout_Slide0_box1_image2,
            ]}
            /*
            prop for <UniversalFrame> & <UniversalCanvas>
            */
            portrait={true}
            /*
            set value of rotation generated by useFrame()
            */
            setRotationYSpeed={0.1}
            /*
            props for "DragRotateStepByStep"
            */
            setDragRotationX={0}
            axisLimitation="x"
            animationDelay={9000}
          />

          <SpinningBox
            groupProps={{
              name: 'groupForSpinningBox_slide_0_Box_2_Data',
              /*
              a bit of responsiveness; 
              */
              scale:
                windowSize.width < minForTablet
                  ? slide0Box2Layout.mobile.scale
                  : slide0Box2Layout.desktop.scale,
              position:
                windowSize.width < minForTablet
                  ? slide0Box2Layout.mobile.position
                  : slide0Box2Layout.desktop.position,
              // ...slide0Box1Layout.mobile,
            }}
            /*
            array of props; using map() we get 4 <SpinningBoxSide>
            */
            spinningBoxConfig={slide0Box2Data}
            /*
            array of images ultimately used in <UniversalCanvas>
            */
            images={[
              containerAbout_Slide0_box2_image1,
              containerAbout_Slide0_box2_image1,
              containerAbout_Slide0_box2_image1,
              containerAbout_Slide0_box2_image1,
            ]}
            /*
            prop for <UniversalFrame> & <UniversalCanvas>
            */
            banner={true}
            /*
            set value of rotation generated by useFrame()
            */
            setRotationYSpeed={-0.1}
            /*
            props for "DragRotateStepByStep"
            */
            setDragRotationX={0}
            axisLimitation="y"
            animationDelay={11000}
          />
        </a.group>
      </Suspense>
    </a.group>
  );
});

export default Slide0Test;

/*
  useEffect Test
  */
// useEffect(() => {
//   console.log('slideId:', slideId);
//   console.log(
//     'canvasGlobalState.containerAboutSlideIndex:',
//     canvasGlobalState.containerAboutSlideIndex
//   );
//   console.log(
//     'canvasGlobalState.currentContainer:',
//     canvasGlobalState.currentContainer
//   );
// }, [
//   slideId,
//   canvasGlobalState.containerAboutSlideIndex,
//   canvasGlobalState.currentContainer,
// ]);
// console.log('textHeader.position:', textHeader.position);
